server:
  servlet:
    context-path: "/dl"
  shutdown: graceful

spring:
  application:
    name: DatalakeService
  lifecycle:
    timeout-per-shutdown-phase: 60

opentracing:
  allowed-header-tags: "uber-trace-id,cdp-destination-api,cdp-caller-id,x-b3-parentspanid,x-b3-traceid,x-b3-spanid,x-b3-sampled,user-agent"
  jaeger:
    log-spans: false

management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: info,health,prometheus
      path-mapping:
        prometheus: metrics
  endpoint:
    metrics:
      enabled: true
      export:
        prometheus:
          enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  metrics:
    distribution:
      sla:
        "[http.server.requests]": "125ms, 250ms, 500ms, 1s, 2s"
      percentiles:
        "[http.server.requests]": "0.5, 0.95"

sdx:
  db:
    aws:
      ha:
        backupretentionperiod: 30
      nonha:
        backupretentionperiod: 0
    azure:
      ha:
        backupretentionperiod: 30
        georedundantbackup: true
      nonha:
        backupretentionperiod: 7
        georedundantbackup: false
    gcp:
      ha:
        backupretentionperiod: 30
      nonha:
        backupretentionperiod: 7
  stack:
    cmsync:
      sleeptime_sec: 10
      duration_min: 10
  gateway:
    topology:
      name: cdp-proxy
    ssotype: SSO_PROVIDER

  paywall.url: "https://archive.cloudera.com/p/cdp-public/"

altus:
  idbmms:
    host: localhost
  ums:
    host: localhost
    caller: datalake
  audit:
    enabled: true
    endpoint: localhost:8982
  datalakedr:
    enabled: false
    endpoint: localhost:8989

datalake:
  cert.dir: /certs/
  client.id: datalake
  structuredevent:
    rest:
      enabled: false
  cloudbreak:
    url: http://localhost:9091
  environmentservice:
    url: http://localhost:8088
  redbeams:
    url: http://localhost:8087
  freeipa:
    url: http://localhost:8090
    contextPath: /freeipa
  db:
    port.5432.tcp:
      port: 5432
      addr: localhost
    env:
      user: postgres
      pass:
      db: datalakedb
      schema: public
      cert.file: database.crt
      ssl: false
  runtimes:
    default: "7.2.14"
    advertised: "7.1.0,7.2.0,7.2.1,7.2.2,7.2.6,7.2.7,7.2.8,7.2.9,7.2.10,7.2.11,7.2.12,7.2.14,7.2.15"
    supported: "7.1.0,7.2.0,7.2.1,7.2.2,7.2.6,7.2.7,7.2.8,7.2.9,7.2.10,7.2.11,7.2.12,7.2.14,7.2.15"
  intermediate.threadpool:
    core.size: 100
    capacity.size: 4000

secret:
  application: sdx/shared
  engine: "com.sequenceiq.cloudbreak.service.secret.vault.VaultKvV2Engine"

cdp.structuredevent:
  rest:
    contentlogging: true

vault:
  addr: localhost
  port: 8200
  ssl.enabled: false
  kv.engine.v2.path: secret
  config.enabled: true
  auth:
    type: "token"
    kubernetes:
      service.account.token.path: /var/run/secrets/kubernetes.io/serviceaccount/token
      mount.path: "dps-dev"
      login.role: "cloudbreak.default"

cb:
  authentication:
    disabled: false
  cm:
    client:
      cluster.proxy.timeout: 120000
      connect.timeout.seconds: 125
      read.timeout.seconds: 125
      write.timeout.seconds: 125
  aws:
    spotinstances.enabled: true
    disabled.instance.types: c5d,f1,i3,m5d,p3dn,r5d,z1d
    hostkey.verify: false
    external.id: provision-ambari
    role.session.name: cdp-provisioning
    cf.template.new.path: templates/aws-cf-stack.ftl
    cf.network.template.path: templates/aws-cf-network.ftl
    cf.template.newdb.path: templates/aws-cf-dbstack.ftl
    default.inbound.security.group:
    vpc:
    vpcendpoints:
      enabled.gateway.services:
      gateway:
        services: s3,dynamodb
      interface:
        services: autoscaling,cloudformation,ec2,ecr.api,ecr.dkr,elasticfilesystem,elasticloadbalancing,sts,rds
    credential.cache.ttl: 60
  gcp:
    hostkey.verify: false
    disk.encryption.url: https://cloud-certs.storage.googleapis.com/google-cloud-csek-ingress.pem
    stopStart.batch.size: 10
    create.batch.size: 5
  azure:
    host.name.prefix.length: 255
    database.template.batchSize: 1
  max:
    azure.resource.name.length: 120
    gcp.resource.name.length: 63
    aws.resource.name.length: 50
    aws.loadbalancer.resource.name.length: 32
    yarn.resource.name.length: 63
  yarn:
    defaultQueue: "default"
    defaultLifeTime: 604800
  platform.default:
    variants: AWS:AWS
    regions: AWS:eu-west-1,AZURE:North Europe,GCP:europe-west1,YARN:default,MOCK:USA

notification:
  urls: http://localhost:3000/notifications

clusterProxy:
  url: http://localhost:10180/cluster-proxy

crn:
  partition: cdp
  region: us-west-1
